apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels
  labels:
    purpose: dev
    app: channels
spec:
  selector:
    matchLabels:
      app: channels

  template:
    metadata:
      labels:
        app: channels

    spec:
      containers:
        - name: channels
          image: channels
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: ENV
              value: local
            #mongo
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_ACCESS_PORT
              value: "27017"
            - name: MONGODB_USER
              value: root
            - name: MONGODB_DATABASE
              value: channels
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
            # rabbitmq
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_ACCESS_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
---
apiVersion: v1
kind: Service
metadata:
  name: channels
  labels:
    app: channels
    service: channels
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: channels

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: channels-ingress
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "false"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /channels
            pathType: ImplementationSpecific
            backend:
              service:
                name: channels
                port:
                  number: 4000
