apiVersion: skaffold/v2beta28
kind: Config
build:
  local:
    concurrency: 0
    push: false
  artifacts:
    - image: channels
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
      - "./dev-k8s.yml"
