apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: communicator-channels
build:
  local:
    concurrency: 1
    push: false
  artifacts:
    - image: channels
      docker:
        dockerfile: Dockerfile.dev
manifests:
  rawYaml:
    - "./dev-k8s.yml"