apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels-service
spec:
  selector:
    matchLabels:
      app: channels-service
  template:
    metadata:
      labels:
        app: channels-service
    spec:
      serviceAccountName: channels-service
      containers:
        - name: channels-service
          image: communicator
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: ENV
              value: dev
            - name: RUN_MIGRATIONS
              value: "true"

          livenessProbe:
            httpGet:
              path: /healthz
              port: container-port

          readinessProbe:
            tcpSocket:
              port: container-port
            initialDelaySeconds: 10
            periodSeconds: 10
