apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels
spec:
  selector:
    matchLabels:
      app: channels
  template:
    metadata:
      labels:
        app: channels
    spec:
      serviceAccountName: channels
      containers:
        - name: channels
          image: communicator
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "384Mi"
              cpu: "200m"
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: ENV
              value: dev
            - name: RUN_MIGRATIONS
              value: "true"

          livenessProbe:
            httpGet:
              path: /healthz
              port: container-port

          readinessProbe:
            tcpSocket:
              port: container-port
            initialDelaySeconds: 20
            periodSeconds: 20
