apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels
spec:
  selector:
    matchLabels:
      app: channels
  template:
    metadata:
      labels:
        app: channels
    spec:
      imagePullSecrets:
        - name: docker-registry
      serviceAccountName: channels
      containers:
        - name: channels
          image: communicator
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "384Mi"
              cpu: "200m"
          ports:
            - name: container-port
              containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: ENV
              value: dev
            #mongo
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_ACCESS_PORT
              value: "27017"
            - name: MONGODB_USER
              value: root
            - name: MONGODB_DATABASE
              value: channels
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
            # rabbitmq
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_ACCESS_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            # cloudflare
            - name: CLOUDFLARE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: cloudflare-account-id
            - name: CLOUDFLARE_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: cloudflare-access-key-id
            - name: CLOUDFLARE_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: cloudflare-secret-access-key
            - name: CLOUDFLARE_R2_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: cloudflare-r2-bucket-name

          livenessProbe:
            httpGet:
              path: /healthz
              port: container-port

          readinessProbe:
            tcpSocket:
              port: container-port
            initialDelaySeconds: 20
            periodSeconds: 20
