apiVersion: v1
kind: Service
metadata:
  name: channels
  labels:
    app: channels
    service: channels
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: channels
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: channels
  labels:
    account: channels
