apiVersion: v1
kind: Service
metadata:
  name: channels-service
  labels:
    app: channels-service
    service: channels-service
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    app: channels-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: channels-service
  labels:
    account: channels-service
