apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: channels
spec:
  hosts:
    - channels
  http:
    - route:
        - destination:
            host: channels
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: connect-failure,refused-stream,503
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: channels
spec:
  host: channels
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
